{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stroom-proxy.fullname" . }}
  labels:
    {{- include "stroom-proxy.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ $.Values.maxClientBodySize }}
    nginx.ingress.kubernetes.io/rewrite-target: /stroom/noauth/datafeed
spec:
  {{- if .Values.ingress.tls }}
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.advertisedHost | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.advertisedHost | quote }}
      http:
        paths:
          - path: /datafeed
            pathType: Exact
            backend:
              service:
                name: {{ include "stroom-proxy.fullname" . }}
                port:
                  name: app
{{- end }}
