apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.clusterConfig | default .Release.Name }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
data:
  stroom-logging-level: {{ .Values.loggingLevel }}
  stroom-proxy-dir: {{ .Values.stroomNode.stroomProxyDir }}
  stroom-service-discovery-enabled: {{ .Values.stroomNode.serviceDiscovery.enabled }}
  {{- with .Values.statisticDocRefs }}
  stat-docref-benchmark-cluster: {{ .benchmarkCluster }}
  stat-docref-cpu: {{ .cpu }}
  stat-docref-events-per-second: {{ .eventsPerSecond }}
  stat-docref-heap-histogram-bytes: {{ .heapHistogramBytes }}
  stat-docref-heap-histogram-instances: {{ .heapHistogramInstances }}
  stat-docref-memory: {{ .memory }}
  stat-docref-metadata-stream-size: {{ .metaDataStreamSize }}
  stat-docref-metadata-streams-received: {{ .metaDataStreamsReceived }}
  stat-docref-pipeline-stream-processor: {{ .pipelineStreamProcessor }}
  stat-docref-stream-task-queue-size: {{ .streamTaskQueueSize }}
  stat-docref-volumes: {{ .volumes }}
  {{- end }}
  auth-account-lockout-threshold: {{ .Values.authService.accountLockoutThreshold }}
  {{- with .Values.authService.password }}
  auth-password-allow-resets: {{ .allowResets }}
  auth-password-force-change-on-first-login: {{ .forceChangeOnFirstLogin }}
  auth-password-max-age: {{ .maxAge }}
  auth-password-max-length: {{ .maxLength }}
  auth-password-complexity-regex: {{ .complexityRegex }}
  {{- end }}
  