apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
data:
  zoo.cfg: |
    dataDir={{ .Values.dataDir }}
    clientPort={{ .Values.global.zookeeper.port }}