{{- if not (lookup "v1" "ConfigMap" .Release.Namespace (include "stroom-node.fullname" .)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stroom-node.fullname" . }}
  labels:
    {{- include "stroom-node.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
data:
  stroom-logging-level: {{ .Values.loggingLevel }}
  stroom-proxy-dir: {{ .Values.stroomProxyDir }}
  stroom-service-discovery-enabled: {{ .Values.serviceDiscovery.enabled | quote }}
  {{- with .Values.statisticDocRefs }}
  stat-docref-benchmark-cluster: {{ .benchmarkCluster }}
  stat-docref-cpu: {{ .cpu }}
  stat-docref-events-per-second: {{ .eventsPerSecond }}
  stat-docref-heap-histogram-bytes: {{ .heapHistogramBytes }}
  stat-docref-heap-histogram-instances: {{ .heapHistogramInstances }}
  stat-docref-memory: {{ .memory }}
  stat-docref-metadata-stream-size: {{ .metaDataStreamSize }}
  stat-docref-metadata-streams-received: {{ .metaDataStreamsReceived }}
  stat-docref-pipeline-stream-processor: {{ .pipelineStreamProcessor }}
  stat-docref-stream-task-queue-size: {{ .streamTaskQueueSize }}
  stat-docref-volumes: {{ .volumes }}
  {{- end }}
{{- end }}