# Example values file for a local Stroom proxy

replicaCount: 1

advertisedHost: "proxy.stroom.example.com"
stroomBaseUri: "stroom.example.com"

forwarding:
  enabled: true

clientKeyStore:
  type: JKS
  secretRef:
    secretName: stroom-proxy-keystore
    key: keystore.jks
  passwordSecretRef:
    secretName: stroom-proxy-keystore-password
    key: password

trustStore:
  type: JKS
  secretRef:
    secretName: stroom-proxy-truststore
    key: truststore.jks
  passwordSecretRef:
    secretName: stroom-proxy-truststore-password
    key: password