# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mysql/mysql-server
  tag: ""

dataDir: /var/lib/mysql

# TODO:
# - Encryption (https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html)
# - Additional custom config (config file?) https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-log-console
# - Logging

# Plain-text configuration to append to the `my.cnf` file
additionalConfig: [ ]
# - key=value

resources:
  requests:
    cpu: 500m
    memory: 512Mi
    storage: 1Gi

  limits:
    cpu: 1000m
    memory: 2Gi
    storage: 2Gi

volumeClaim:
  volumeName: ""
  storageClassName: ""
  selector:
    matchLabels: { }
    matchExpressions: { }
  dataSource: { }
  accessModes:
    - ReadWriteOnce
  volumeMode: { }

podAnnotations: { }

podSecurityContext: { }
  # fsGroup: 1000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: { }

tolerations: [ ]

affinity: { }
