# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: zookeeper
  tag: ""

jvmOpts: -Xms50m -Xmx1024m

# Number of milliseconds comprising one tick (unit of time)
tickTime: 2000

# Number of ticks to allow for followers to connect and sync to a leader
initLimit: 30

volumeClaim:
  volumeName: ""
  storageClassName: ""
  selector:
    matchLabels: { }
    matchExpressions: { }
  dataSource: { }
  accessModes:
    - ReadWriteOnce
  volumeMode: { }

podAnnotations: { }

podSecurityContext: { }
  # fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
    storage: 1Gi

  limits:
    cpu: 1000m
    memory: 2Gi
    storage: 2Gi

nodeSelector: { }

tolerations: [ ]

affinity: { }
