{{- if not (lookup "v1" "ConfigMap" .Release.Namespace (include "auth-service.fullname" .)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
data:
  account-lockout-threshold: {{ .Values.accountLockoutThreshold | quote }}
  password-allow-resets: {{ .Values.password.allowPasswordResets | quote }}
  {{- with .Values.password }}
  password-force-change-on-first-login: {{ .forceChangeOnFirstLogin | quote }}
  password-max-age: {{ .maxAge | quote }}
  password-max-length: {{ .maxLength | quote }}
  password-complexity-regex: {{ .complexityRegex | quote }}
  {{- end }}
{{- end }}