{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ $.Values.global.advertisedHost }}
      secretName: {{ required "Ingress TLS secret name is required" .Values.global.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.global.advertisedHost }}
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-service.fullname" . }}
                port:
                  name: auth
{{- end }}