apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $name, $number := .Values.ports }}
    - port: {{ $number }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
