kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-mgm
data:
  mysql-cluster.cnf: |
    [ndbd default]
    NoOfReplicas={{ .Values.mysql.dataNode.replicas }}
    DataMemory=80M

    {{- range $managementNodeId, $replicas := until (.Values.mysql.managementNode.replicas | int) }}
    [ndb_mgmd]
    HostName={{ printf "%s-mgm-%d" (include "mysql-cluster.fullname" $) $managementNodeId }}
    PortNumber={{ $.Values.mysql.ports.management }}
    DataDir=/var/lib/mysql
    {{- end }}

    {{- range $dataNodeId, $replicas := until (.Values.mysql.dataNode.replicas | int) }}
    [ndbd]
    HostName={{ printf "%s-data-%d.%s-data" (include "mysql-cluster.fullname" $) $dataNodeId (include "mysql-cluster.fullname" $) }}
    {{- end }}

    {{- range $i, $clientConnections := until (.Values.mysql.sqlNode.replicas | int) }}
    [mysqld]
    {{- end }}