{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}
  labels:
    {{- include "solr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.global.solr.port }}
      targetPort: solr
      protocol: TCP
      name: solr
  selector:
    {{- include "solr.selectorLabels" . | nindent 4 }}
{{- end }}