{{- $component := "smtp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stroom.fullname" . }}-{{ $component }}
  labels:
    {{- include "stroom.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.smtp.replicaCount }}
  selector:
    matchLabels:
      {{- include "stroom.selectorLabels" . | nindent 6 }}
      component: {{ $component }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stroom.selectorLabels" . | nindent 8 }}
        component: {{ $component }}
    spec:
      serviceAccountName: {{ include "stroom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.smtp.image.repository }}:{{ .Values.smtp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: {{ .Values.smtp.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.smtp.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
