{{- $component := "smtp" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stroom.fullname" . }}-{{ $component }}
  labels:
    {{- include "stroom.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.global.smtp.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "stroom.selectorLabels" . | nindent 4 }}
    component: {{ $component }}
