{{- if .Values.global.ingress.enabled -}}
{{- $httpPort := "http" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth-ui.fullname" . }}
  labels:
    {{- include "auth-ui.labels" . | nindent 4 }}
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ $.Values.global.advertisedHost }}
      secretName: {{ required "Ingress TLS secret name is required" .Values.global.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.global.advertisedHost }}
      http:
        paths:
          - path: /authui
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-ui.fullname" . }}
                port:
                  name: {{ $httpPort }}
          - path: /config.json
            pathType: Exact
            backend:
              service:
                name: {{ include "auth-ui.fullname" . }}
                port:
                  name: {{ $httpPort }}
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-ui.fullname" . }}
                port:
                  name: {{ $httpPort }}
          - path: /s
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-ui.fullname" . }}
                port:
                  name: {{ $httpPort }}
{{- end }}