apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-ui.fullname" . }}
  labels:
    {{- include "auth-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.authUi.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auth-ui.selectorLabels" . | nindent 4 }}
