apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-ui.fullname" . }}
  labels:
    {{- include "auth-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $name, $number := .Values.global.authUi.ports }}
    - port: {{ $number }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "auth-ui.selectorLabels" . | nindent 4 }}
