{{- $nodeType := "server" }}
{{- $rootPasswordFile := "/etc/mysql/password/root" }}
{{- $serviceUserPasswordFile := "/etc/mysql/password/serviceuser" }}
{{- $passwordFileMode := 0777 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-{{ $nodeType }}
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mysql.serverNode.replicas }}
  serviceName: {{ include "mysql-cluster.fullname" . }}-server
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "mysql-cluster.selectorLabels" . | nindent 6 }}
      nodeType: {{ $nodeType }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql-cluster.selectorLabels" . | nindent 8 }}
        nodeType: {{ $nodeType }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ $rootPasswordFile }}
            {{- if .Values.mysql.serviceUser.userName }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.serviceUser.userName }}
            - name: MYSQL_PASSWORD
              value: {{ $serviceUserPasswordFile }}
            {{- end }}
          args:
            - mysqld
          ports:
            - name: {{ $nodeType }}
              containerPort: {{ .Values.mysql.ports.mysqld }}
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            tcpSocket:*/}}
{{/*              port: data*/}}
{{/*          readinessProbe:*/}}
{{/*            initialDelaySeconds: 15*/}}
{{/*            tcpSocket:*/}}
{{/*              port: data*/}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/my.cnf
              subPath: my.cnf
              name: config
              readOnly: true
            - mountPath: {{ .Values.mysql.node.dataDir }}
              name: data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-scripts
              readOnly: true
            - mountPath: {{ $rootPasswordFile }}
              subPath: root
              name: root-password
              readOnly: true
            {{- if .Values.mysql.serviceUser.userName }}
            - mountPath: {{ $serviceUserPasswordFile }}
              subPath: serviceuser
              name: serviceuser-password
              readOnly: true
            {{- end }}
      serviceAccountName: {{ include "mysql-cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "mysql-cluster.fullname" . }}-{{ $nodeType }}
        - name: init-scripts
          configMap:
            name: {{ include "mysql-cluster.fullname" . }}-initscripts
        - name: root-password
          secret:
            {{- if .Values.mysql.rootUser.secret.name }}
            secretName: {{ .Values.mysql.rootUser.secret.name }}
            items:
              - key: {{ .Values.mysql.rootUser.secret.key }}
                path: root
                mode: {{ $passwordFileMode }}
            {{- else }}
            secretName: {{ include "mysql-cluster.fullname" . }}-rootuser
            items:
              - key: password
                path: root
                mode: {{ $passwordFileMode }}
            {{- end }}
        {{- if .Values.mysql.serviceUser.userName }}
        - name: serviceuser-password
          secret:
            {{- if .Values.mysql.serviceUser.secret.name }}
            secretName: {{ .Values.mysql.serviceUser.secret.name }}
            items:
              - key: {{ .Values.mysql.serviceUser.secret.key }}
                path: serviceuser
                mode: {{ $passwordFileMode }}
            {{- else }}
            secretName: {{ include "mysql-cluster.fullname" . }}-serviceuser
            items:
              - key: password
                path: serviceuser
                mode: {{ $passwordFileMode }}
            {{- end }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "mysql-cluster.labels" . | nindent 10 }}
      spec:
        volumeName: {{ .Values.volumeClaim.volumeName | quote }}
        storageClassName: {{ .Values.volumeClaim.storageClassName | quote }}
        selector:
          matchLabels:
            mysql/clusterId: {{ $.Values.mysql.clusterId }}
            mysql/nodeType: {{ $nodeType }}
            {{- with .Values.volumeClaim.selector.matchLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.volumeClaim.selector.matchExpressions }}
          matchExpressions:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.volumeClaim.dataSource }}
        dataSource:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeClaim.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeClaim.volumeMode }}
        volumeMode:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeClaim.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}