# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mysql/mysql-cluster
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

mysql:
  # User databases to create on startup
  initDatabases: []

  rootUser:
    # If set, use an existing secret to determine the initial password of the user 'root'
    secret:
      name: ""
      key: password

    # If set, assigns a password from plain text (only use this in development!)
    password: ""

    # Path to the file containing the root user password
    passwordFromFile: ""

    # If none of these are specified, a secret is generated automatically
  serviceUser:
    # If set, creates a separate user account with ownership over user application databases
    userName: stroom
    # Host the user is permitted to login from (defaults to any)
    host: "%"
    secret:
      name: ""
      key: password
    password: ""
    passwordFromFile: ""
  ports:
    management: 1186
    data: 2202
    mysqld: 3306

  node:
    dataDir: /var/lib/mysql
    connectionRetries: 10
  managementNode:
    replicas: 1
  dataNode:
    replicas: 2
    lockPagesInMainMemory: true

    # Generally this should be >= the amount of data stored, plus a 20% margin
    dataMemory: 100M

    # Enable for Linux systems with kernel version >= 2.6
    oDirectWrites: false
  sqlNode:
    # Maximum number of slots available for SQL client nodes
    replicas: 3

clusterName: cluster.local

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
