# Default values for stroom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Identifies this Stroom deployment
  stackName: stroom-dev

  # Used to logically identify groups of nodes
  rackName: rack-1

  # Set the advertised host (could be a FQDN or hostname)
  advertisedHost: "stroom"

  ingress:
    enabled: true
    tls:
      secretName: "stroom-tls"
    annotations:
      kubernetes.io/ingress.class: nginx

  authService:
    chartId: auth-service

  authUi:
    chartId: auth-ui

    ports:
      http: 5000
      https: 9443

  kafka:
    chartId: kafka

    # Override the service name. Defaults to: (Release name)-kafka
    serviceName: ""
    port: 9092
    # TODO: Review use of version - add to global scope?
    connectorVersion: 2.1.1

  mysql:
    chartId: mysql

    # MySQL service port
    port: 3307

    users:
      root:
        password: ""
      service:
        name: "stroomuser"
        password: ""

    # User databases to create on startup
    databases:
      annotations: annotations
      auth: auth
      config: config
      datameta: datameta
      explorer: explorer
      process: process
      stats: stats
      stroom: stroom

  smtp:
    chartId: smtp

    port: 2525
    transport: plain

  stroomNode:
    chartId: stroom-node

  zookeeper:
    chartId: zookeeper

    replicaCount: 3
    port: 2181

# Number of characters to generate for random passwords
randomPasswordLength: 16

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
  # fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: { }

tolerations: [ ]

affinity: { }
