apiVersion: v1
kind: Service
metadata:
  name: {{ include "stroom.fullname" . }}
  labels:
    {{- include "stroom.labels" . | nindent 4 }}
    component: ""
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stroom.selectorLabels" . | nindent 4 }}
