{{- $component := "process-node" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stroom.fullname" . }}-{{ $component }}
  labels:
    {{- include "stroom.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processNode.replicaCount }}
  selector:
    matchLabels:
      {{- include "stroom.selectorLabels" . | nindent 6 }}
      component: {{ $component }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stroom.selectorLabels" . | nindent 8 }}
        component: {{ $component }}
    spec:
      serviceAccountName: {{ include "stroom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.processNode.image.repository }}:{{ .Values.processNode.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.processNode.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
