mysql:
  clusterId: stroom
  initDatabases:
    - annotations
    - auth
    - config
    - datameta
    - explorer
    - process
    - stats
    - stroom

  rootUser:
    password: "test"
    secret:
      name: ""
    passwordFromFile: ""
  serviceUser:
    password: ""
    secret:
      name: ""
      passwordFromFile: ""
  managementNode:
    replicas: 1
  dataNode:
    replicas: 2
  sqlNode:
    replicas: 3

podSecurityContext: {}
  # fsGroup: 27 # mysql

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 27 # mysql

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

volumeClaim:
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
