global:
  stackName: stroom-dev

  # Must be changed
  advertisedHost: stroom.example.com

  ingress:
    tls:
      # A secret must be pre-created in the SAME namespace using this name
      secretName: "stroom-tls"

  mysql:
    users:
      root:
        password: "test"
      service:
        password: "test"

stroom-node:
  replicaCount: 3

  sharedDataVolume:
    nfs:
      server: file-server.example.com
      path: /data

kafka:
  externalListener:
    host: 192.168.1.1
    targetPort: 9093
    externalPort: 30093

mysql:
  additionalConfig:
    - slow_query_log
    - long_query_time=0.001