apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.global.kafka.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
