# Default values for stroom-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gchq/stroom-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

busybox:
  repository: busybox

nameOverride: ""
fullnameOverride: ""

logging:
  level: WARN
  archive:
    enabled: true
    maxFileCount: 3600
  timeZone: UTC
  baseDir: /stroom-proxy/logs
  fileDateFormat: yyyy-MM-dd-HH-mm

logSender:
  enabled: true
  image:
    repository: gchq/stroom-log-sender
    tag: v2.2.0
  cronSchedule: "* * * * *"
  fileRegex: .*\.gz$
  sources: # Map of subdirectories to feed names
    app: STROOM_PROXY-APP-EVENTS
    access: STROOM_PROXY-ACCESS-EVENTS
    receive: STROOM_PROXY-RECEIVE-EVENTS
    send: STROOM_PROXY-SEND-EVENTS
  attributes:
    system: Stroom Proxy v7
    environment: Production
  extraHeaders: { }
#    SecurityDomain: Unclassified
  destinationUrl: https://stroom.example.com/stroom/datafeed
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 64Mi

receive:
  authenticationRequired: false
  certificateAuthentication:
    enabled: false

stroom:
  baseUri: http://stroom-node.stroom.svc:8080
  paths:
    datafeed: /stroom/noauth/datafeed
    feedStatus: /api/feedStatus/v1
  feedStatus:
    enabled: true
    connectionTimeout: 1s
    timeout: 3s
    timeToLive: 1h
    # Stroom API key to enable feed status lookups.
    apiKeySecretRef:
      name: ""
      key: ""
  tls:
    verifyHostName: true
    trustSelfSignedCertificates: false

forwarding:
  # Whether to forward to another proxy. If disabled, `clientKeyStore` and `trustStore` options are ignored.
  enabled: true

  # Override the forwarding URL. By default, `{stroom.baseUri}/stroom/noauth/datafeed` is used.
  url: ""

  # Maximum chunk size in bytes. Set to `0` to disable chunked encoding
  maxChunkSize: 1048576

  tls:
    verifyHostName: true

threads:
  examineSource: 4
  forwarding: 4
  forwardRetry: 2

db:
  dbDir: db

repository:
  storing:
    enabled: true

  aggregation:
    enabled: true
    frequency: PT1M
    maxAge: PT10M

    # Maximum number of files to include in a single aggregate, before rolling over
    maxItems: 10000

    # Stream size (uncompressed) to break at when building an aggregate
    maxUncompressedSizeBytes: 1.0G

# Used for client connections to Stroom or a downstream proxy
keyStore:
  type: PKCS12 # PKCS12|JKS
  secretRef:
    name: ""
    key: keystore.p12
  passwordSecretRef:
    name: ""
    key: ""

trustStore:
  type: PKCS12 # PKCS12, JKS
  secretRef:
    name: ""
    key: truststore.p12
  passwordSecretRef:
    name: ""
    key: ""

restClient:
  timeout: 10s
  connectionTimeout: 10s
  timeToLive: 1h
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0

ports:
  app: 8090
  admin: 8091
  debug: 10766

tls:
  # Enable TLS for the backend proxy service
  enabled: false
  secretName: ""

ingress:
  enabled: true
  className: nginx
  hostName: "" # stroom-proxy.example.com
  annotations: { } # Extra annotations to add to the Ingress resource
  # Maximum size of an HTTP POST to the ingress. Ensure this is large enough to cater for posted event files
  maxClientBodySize: 10g
  tls:
    secretName: ""

# Override Dropwizard server properties: https://www.dropwizard.io/en/latest/manual/configuration.html#all
serverProperties: { }
#  idleThreadTimeout: 1 minute

takeOwnershipOnStartup: false

volumeClaims:
  # Local proxy storage. Recommend using fast storage tier especially when aggregation is enabled
  data: { }
#    storageClassName: ""
#    selector:
#      matchLabels: { }
#      matchExpressions: { }
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ""
#      limits:
#        storage: ""

extraEnv: [ ]
#  - name: ENV_VAR
#    value: "123"

extraVolumes: [ ]
#  - name: data
#    nfs:
#      server: fs.example.com
#      path: /stroom-proxy

extraVolumeMounts: [ ]
#  - mountPath: /stroom-proxy/data
#    name: data

javaOpts: -Xms512m -Xmx1g

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

probeTimings:
  startup:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 10
    failureThreshold: 3

podAnnotations: { }

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: { }
tolerations: [ ]
affinity: { }
