# Default values for stroom-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gchq/stroom-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

advertisedHost: stroom-proxy.example.com

stroom:
  host: stroom-node.stroom.svc
  port: 8080
  apiScheme: http # http, https
  apiKey:
    # Requires:
    # - stroom_api_key - API key issued by Stroom, to enable feed status lookups. Secret key is `stroom_api_key`
    secretRef:
      secretName: ""
      key: ""

storing:
  enabled: true

forwarding:
  # Whether to forward to another proxy. If disabled, `clientKeyStore` and `trustStore` options are ignored.
  enabled: true

  scheme: http # http, https

  # Number of threads to forward with
  threadCount: 4

repository:
  # How often to scan the repository
  readCron: "* * *"

  # Max number of files to scan over during forwarding. Once this limit is reached it will wait until next read interval
  maxFileScan: 100000

  # The maximum number of concurrent mapped files we can hold before we send the largest set for aggregation
  maxConcurrentMappedFiles: 100000

  # Stream size (uncompressed) to break at when building an aggregate
  maxUncompressedSizeBytes: 1G

  # Maximum number of files to include in a single aggregate, before rolling over
  maxFilesPerAggregate: 10000

# Used for client connections to Stroom or a downstream proxy
clientKeyStore:
  type: "" # PKCS12, JKS, ...
  secretRef:
    secretName: ""
    key: "keystore.jks" # keystore.jks
  passwordSecretRef:
    secretName: ""
    key: "password"

trustStore:
  type: "" # PKCS12, JKS
  secretRef:
    secretName: ""
    key: "" # truststore.jks
  passwordSecretRef:
    secretName: "truststore.jks"
    key: "password"

# Maximum size of a HTTP POST to the ingress. Ensure this is large enough to cater for posted event files
maxClientBodySize: 10g

webServer:
  timeout: 10s
  connectionTimeout: 10s
  timeToLive: 1h
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  verifyHostname: true
  trustSelfSignedCertificates: false

ports:
  app: 8090
  admin: 8091
  debug: 10766

volumeClaims:
  # Local proxy storage. Recommend using fast storage tier especially when aggregation is enabled
  localData:
    volumeName: ""
    storageClassName: ""
    selector:
      matchLabels: {}
      matchExpressions: {}
    dataSource: {}
    accessModes:
      - ReadWriteOnce
    volumeMode: {}

sharedProxyRepoVolume: {}
  # nfs:
  #   server: file-server.example.com
  #   path: /data

ingress:
  enabled: true
  className: nginx
  annotations: {} # Extra annotations to add to the Ingress resource
  tls:
    secretName: ""

javaOpts: -Xms512m -Xmx1g -Xrunjdwp:server=y,transport=dt_socket,address=10765,suspend=n

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
    storage: 1Gi

  limits:
    cpu: 2000m
    memory: 2Gi
    storage: 2Gi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 10
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 5

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
