# Default values for stroom-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gchq/stroom-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

logging:
  level: WARN
  archive:
    enabled: true
    maxFileCount: 90
  timeZone: UTC
  baseDir: /stroom-proxy/logs
  fileDateFormat: yyyy-MM-dd

stroom:
  baseUri: http://stroom-node.stroom.svc:8080
  paths:
    datafeed: /stroom/noauth/datafeed
    feedStatus: /api/feedStatus/v1
  # Stroom API key to enable feed status lookups
  apiKeySecretRef:
    name: ""
    key: ""
  tls:
    verifyHostName: true
    trustSelfSignedCertificates: false

forwarding:
  # Whether to forward to another proxy. If disabled, `clientKeyStore` and `trustStore` options are ignored.
  enabled: true

  # Override the forwarding URL. By default, `{stroom.baseUri}/stroom/noauth/datafeed` is used.
  url: ""

  # Number of threads to forward with
  threadCount: 4

  # Perform X.509 host verification
  hostVerificationEnabled: true

repository:
  # Folder structure
  format: "${pathId}/${id}"

  storing:
    enabled: true

  reader:
    # How often to scan the repository
    cronSchedule: "* * *"

    # Max number of files to scan over during forwarding. Once this limit is reached it will wait until next read interval
    maxFileScan: 100000

    # The maximum number of concurrent mapped files we can hold before we send the largest set for aggregation
    maxConcurrentMappedFiles: 100000

  aggregation:
    # Stream size (uncompressed) to break at when building an aggregate
    maxStreamSize: 1G

    # Maximum number of files to include in a single aggregate, before rolling over
    maxFilesPerAggregate: 10000

# Used for client connections to Stroom or a downstream proxy
keyStore:
  type: PKCS12 # PKCS12|JKS
  secretRef:
    name: ""
    key: keystore.jks
  passwordSecretRef:
    name: ""
    key: ""

trustStore:
  type: PKCS12 # PKCS12, JKS
  secretRef:
    name: ""
    key: truststore.jks
  passwordSecretRef:
    name: ""
    key: ""

webServer:
  timeout: 10s
  connectionTimeout: 10s
  timeToLive: 1h
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  verifyHostname: true
  trustSelfSignedCertificates: false

ports:
  app: 8090
  admin: 8091
  debug: 10766

volumeClaims:
  # Local proxy storage. Recommend using fast storage tier especially when aggregation is enabled
  data: { }
#    storageClassName: ""
#    selector:
#      matchLabels: { }
#      matchExpressions: { }
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ""
#      limits:
#        storage: ""

extraEnv: [ ]
#  - name: ENV_VAR
#    value: "123"

extraVolumes: [ ]
#  - name: data
#    nfs:
#      server: fs.example.com
#      path: /stroom-proxy

extraVolumeMounts: [ ]
#  - mountPath: /stroom-proxy/data
#    name: data

ingress:
  enabled: true
  className: nginx
  hostName: stroom-proxy.example.com
  annotations: { } # Extra annotations to add to the Ingress resource
  # Maximum size of an HTTP POST to the ingress. Ensure this is large enough to cater for posted event files
  maxClientBodySize: 10g
  tls:
    secretName: ""

javaOpts: -Xms512m -Xmx1g

resources:
  requests:
    cpu: 1000m
    memory: 1Gi

  limits:
    cpu: 2000m
    memory: 2Gi

probeTimings:
  startup:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 10
    failureThreshold: 3

podAnnotations: { }

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

nodeSelector: { }
tolerations: [ ]
affinity: { }
