apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.mysql.serviceName | default (print .Release.Name "-mysql") }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.global.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
