# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gchq/stroom
  tag: ""

javaOpts: -Xms50m -Xmx1024m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=10765,suspend=n
jpaDialect: org.hibernate.dialect.MySQLInnoDBDialect
jdbcDriver: com.mysql.cj.jdbc.Driver

# Node name prefix used to generate node IDs. For instance, the first node will be called 'node-1'
# TODO: Label nodes using this prefix
nodeNamePrefix: node

# Development mode
developmentMode: false

contentPackImportEnabled: false

loggingLevel: INFO

serviceDiscovery:
  enabled: true

stroomProxyDir: /tmp/proxy

stroomHelpUrl: https://gchq.github.io/stroom-docs

statisticDocRefs:
  benchmarkCluster: docRef(StatisticStore,946a88c6-a59a-11e6-bdc4-0242ac110002,Benchmark-Cluster Test)
  cpu: docRef(StatisticStore,af08c4a7-ee7c-44e4-8f5e-e9c6be280434,CPU)
  eventsPerSecond: docRef(StatisticStore,a9936548-2572-448b-9d5b-8543052c4d92,EPS)
  heapHistogramBytes: docRef(StatisticStore,934a1600-b456-49bf-9aea-f1e84025febd,Heap Histogram Bytes)
  heapHistogramInstances: docRef(StatisticStore,e4f243b8-2c70-4d6e-9d5a-16466bf8764f,Heap Histogram Instances)
  memory: docRef(StatisticStore,77c09ccb-e251-4ca5-bca0-56a842654397,Memory)
  metaDataStreamSize: docRef(StatisticStore,946a8814-a59a-11e6-bdc4-0242ac110002,Meta Data-Stream Size)
  metaDataStreamsReceived: docRef(StatisticStore,946a87bc-a59a-11e6-bdc4-0242ac110002,Meta Data-Streams Received)
  pipelineStreamProcessor: docRef(StatisticStore,946a80fc-a59a-11e6-bdc4-0242ac110002,PipelineStreamProcessor)
  streamTaskQueueSize: docRef(StatisticStore,946a7f0f-a59a-11e6-bdc4-0242ac110002,Stream Task Queue Size)
  volumes: docRef(StatisticStore,ac4d8d10-6f75-4946-9708-18b8cb42a5a3,Volumes)

volumeClaim:
  volumeName: ""
  storageClassName: ""
  selector:
    matchLabels: { }
    matchExpressions: { }
  dataSource: { }
  accessModes:
    - ReadWriteOnce
  volumeMode: { }

podAnnotations: { }

podSecurityContext: { }
  # fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
    storage: 1Gi

  limits:
    cpu: 2000m
    memory: 2Gi
    storage: 2Gi

nodeSelector: { }

tolerations: [ ]

affinity: { }
