apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-server
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: server
      protocol: TCP
      name: server
