kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mysql-cluster.fullname" . }}
data:
  my.cnf: |
    [mysqld]
    ndbcluster
    datadir={{ .Values.mysql.node.dataDir }}
    port={{ $.Values.mysql.serverNode.port }}
    user={{ .Values.securityContext.runAsUser | default "mysql" }}
    ndb-connectstring={{ include "mysql-cluster.fullname" . }}-management:{{ .Values.mysql.managementNode.port }}

    [mysql_cluster]
    connect-string={{ include "mysql-cluster.fullname" . }}-management:{{ .Values.mysql.managementNode.port }}

  mysql-cluster.cnf: |
    [ndb_mgmd default]
    PortNumber={{ .Values.mysql.managementNode.port }}
    DataDir={{ .Values.mysql.node.dataDir }}

    {{- $currentNodeId := .Values.mysql.managementNode.nodeIdStartAt }}

    {{- range $managementNodeId, $replicas := until (.Values.mysql.managementNode.replicas | int) }}
    [ndb_mgmd]
    HostName={{ printf "%s-management-%d.%s-management.%s.svc.%s" (include "mysql-cluster.fullname" $ ) $managementNodeId (include "mysql-cluster.fullname" $ ) $.Release.Namespace $.Values.clusterName }}
    NodeId={{ $currentNodeId }}
    {{ $currentNodeId = (add $currentNodeId 1) }}
    {{- end }}

    [ndbd default]
    NoOfReplicas={{ .Values.mysql.dataNode.replicas }}
    DataDir={{ .Values.mysql.node.dataDir }}
    DataMemory={{ .Values.mysql.dataNode.dataMemory }}

    {{- if .Values.mysql.dataNode.lockPagesInMainMemory }}
    LockPagesInMainMemory=1
    {{- end }}

    {{- if .Values.mysql.dataNode.oDirectWrites }}
    ODirect=1
    {{- end }}

    {{- $currentNodeId = .Values.mysql.dataNode.nodeIdStartAt }}

    {{- range $dataNodeId, $replicas := until (.Values.mysql.dataNode.replicas | int) }}
    [ndbd]
    HostName={{ printf "%s-data-%d.%s-data.%s.svc.%s" (include "mysql-cluster.fullname" $ ) $dataNodeId (include "mysql-cluster.fullname" $ ) $.Release.Namespace $.Values.clusterName }}
    NodeId={{ $currentNodeId }}
    {{ $currentNodeId = (add $currentNodeId 1) }}
    {{- end }}

    {{- $currentNodeId = .Values.mysql.serverNode.nodeIdStartAt }}

    {{- range $sqlNodeId, $clientConnections := until (.Values.mysql.serverNode.replicas | int) }}
    [mysqld]
    NodeId={{ $currentNodeId }}
    {{ $currentNodeId = (add $currentNodeId 1) }}
    {{- end }}