kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-initscripts
data:
  init-stroom-db.sql: |
    -- Script to initialise Stroom databases

    {{/* For each database, create it if it doesn't exist and grant access to the service user account */}}
    {{- range .Values.mysql.databases }}
    CREATE DATABASE IF NOT EXISTS {{ . }};
    GRANT ALL PRIVILEGES ON {{ . }}.* TO '{{ $.Values.mysql.serviceUser.userName }}'@'{{ $.Values.mysql.serviceUser.host }}';
    {{ "" }}
    {{- end }}

    SELECT 'Dumping list of databases' AS '';
    SELECT '---------------------------------------' AS '';
    SHOW DATABASES;

    SELECT 'Dumping list of users' AS '';
    SELECT '---------------------------------------' AS '';
    SELECT User AS 'USER', Host AS 'HOST' FROM mysql.user;