{{ $rootUser := .Values.mysql.rootUser }}
{{- if not $rootUser.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-rootuser
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $rootUser.password }}
  password: {{ $rootUser.password | b64enc }}
  {{- else if $rootUser.passwordFromFile }}
  {{- /* Parse password from the specified file and encode in base64 */}}
  password: {{ (.Files.Get $rootUser.passwordFromFile) | b64enc }}
  {{- else }}
  {{- /* Generate a random password */}}
  password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
{{- end }}
---
{{ $serviceUser := .Values.mysql.serviceUser }}
{{- if not $serviceUser.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-serviceuser
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $serviceUser.password }}
  password: {{ $serviceUser.password | b64enc }}
  {{- else if $serviceUser.passwordFromFile }}
  password: {{ (.Files.Get $serviceUser.passwordFromFile) | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
{{- end }}